apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
stringData:
  apikey: 'your-api-key'
  apisecret: 'your-api-secret'
  registry-apikey: 'your-registry-api-key'
  registry-apisecret: 'your-registry-api-secret'
