apiVersion: v1
kind: Service
metadata:
  name: pipeline-{{PIPELINE_ID}}-metrics
  namespace: inflect
  labels:
    app: pipeline-{{PIPELINE_ID}}
spec:
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: pipeline-{{PIPELINE_ID}}
